analyze_sweeps_2(R_list_pre, false, true, "Angle", "Height", ...
    {"Height", "\mu m", h, h(12), 0.01}, ...
    {"Pitch", "\mu m", d1, d1(4), 0.01}, ...
    {"Radius", "%", r(1), r(1), 0.01}, ...
    {"Wavelength", "\mu m", wlr, wlr(3), 0.02}, ...
    {"Angle", "Deg", phi, phi(1), 1})